<a href="https://colab.research.google.com/github/HonoreT/AtelierSYMBIOSOL/blob/main/00_Setup_Inventory_Charlotte_DNA_SIP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Étape 5 — Monter Google Drive**

In [3]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

**Étape 6 — Définir les chemins du projet**

In [6]:
from pathlib import Path

PROJECT_NAME = "Charlotte_DNA_SIP"

DRIVE_ROOT = Path("/content/drive/MyDrive") / PROJECT_NAME
WORK_ROOT = Path("/content") / PROJECT_NAME

RAW_ROOT = DRIVE_ROOT / "02_raw_fastq"
METADATA_ROOT = DRIVE_ROOT / "01_metadata"
CLASSIFIER_ROOT = DRIVE_ROOT / "03_classifiers"
DRIVE_RESULTS = DRIVE_ROOT / "05_results"
EXPORT_ROOT = DRIVE_ROOT / "06_exports"
LOG_ROOT = DRIVE_ROOT / "07_logs"

WORK_RESULTS = WORK_ROOT / "results"

required_directories = [
    DRIVE_ROOT / "00_documentation",
    METADATA_ROOT,
    RAW_ROOT / "run3" / "16S",
    RAW_ROOT / "run4" / "ITS2",
    RAW_ROOT / "run5" / "16S",
    RAW_ROOT / "run5" / "ITS2",
    CLASSIFIER_ROOT,
    DRIVE_RESULTS / "16S" / "run3",
    DRIVE_RESULTS / "16S" / "run5",
    DRIVE_RESULTS / "16S" / "merged",
    DRIVE_RESULTS / "ITS2" / "run4",
    DRIVE_RESULTS / "ITS2" / "run5",
    DRIVE_RESULTS / "ITS2" / "merged",
    EXPORT_ROOT,
    LOG_ROOT,
    WORK_RESULTS,
]

for directory in required_directories:
    directory.mkdir(parents=True, exist_ok=True)

print("Projet Drive :", DRIVE_ROOT)
print("Espace temporaire Colab :", WORK_ROOT)

Projet Drive : /content/drive/MyDrive/Charlotte_DNA_SIP
Espace temporaire Colab : /content/Charlotte_DNA_SIP

**Étape 7 — Installer QIIME 2**

In [7]:
!rm -rf /content/AtelierSYMBIOSOL

!git clone \
  https://github.com/HonoreT/AtelierSYMBIOSOL.git \
  /content/AtelierSYMBIOSOL

Cloning into '/content/AtelierSYMBIOSOL'...
remote: Enumerating objects: 328, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 328 (delta 10), reused 7 (delta 7), pack-reused 312 (from 1)
Receiving objects: 100% (328/328), 413.13 MiB | 34.80 MiB/s, done.
Resolving deltas: 100% (115/115), done.
Updating files: 100% (79/79), done.

Puis :

In [8]:
%run /content/AtelierSYMBIOSOL/setup_qiime2

[15:14:18] 🐍 Downloading miniforge...                                                              ]8;id=864969;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=109644;file:///content/AtelierSYMBIOSOL/setup_qiime2#73\73]8;;\

[15:14:19] 🐍 Done.                                                                                 ]8;id=779119;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=542792;file:///content/AtelierSYMBIOSOL/setup_qiime2#79\79]8;;\

           🐍 Installing miniforge...                                                               ]8;id=426571;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=333735;file:///content/AtelierSYMBIOSOL/setup_qiime2#73\73]8;;\

[15:14:32] 🐍 Installed miniforge to `/usr/local`.                                                  ]8;id=63932;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=906689;file:///content/AtelierSYMBIOSOL/setup_qiime2#79\79]8;;\

           🔍 Downloading Qiime 2 package list...                                                   ]8;id=262135;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=624098;file:///content/AtelierSYMBIOSOL/setup_qiime2#73\73]8;;\

[15:14:33] 🔍 Done.                                                                                 ]8;id=327430;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=452737;file:///content/AtelierSYMBIOSOL/setup_qiime2#79\79]8;;\

           🔍 Installing Qiime 2 (2025.4). This may take a little bit.                              ]8;id=563790;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=639530;file:///content/AtelierSYMBIOSOL/setup_qiime2#73\73]8;;\
            🕐

[15:20:10] 🔍 Done.                                                                                 ]8;id=914099;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=249312;file:///content/AtelierSYMBIOSOL/setup_qiime2#79\79]8;;\

           🐧 Setting up the Qiime2 command...                                                     ]8;id=602632;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=663050;file:///content/AtelierSYMBIOSOL/setup_qiime2#101\101]8;;\

           🐧 Done.                                                                                ]8;id=931976;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=571342;file:///content/AtelierSYMBIOSOL/setup_qiime2#107\107]8;;\

           🌲 Installing empress...                                                                ]8;id=361996;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=406270;file:///content/AtelierSYMBIOSOL/setup_qiime2#151\151]8;;\

           🐍 Activating the qiime2 environment.                                                    ]8;id=393333;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=999404;file:///content/AtelierSYMBIOSOL/setup_qiime2#89\89]8;;\

[15:22:30] 🌲 Done.                                                                                ]8;id=220811;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=520801;file:///content/AtelierSYMBIOSOL/setup_qiime2#157\157]8;;\

           📊 Checking that Qiime 2 command line works...                                           ]8;id=470704;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=220752;file:///content/AtelierSYMBIOSOL/setup_qiime2#73\73]8;;\

[15:23:19] 📊 Qiime 2 command line looks good 🎉                                                    ]8;id=921325;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=682396;file:///content/AtelierSYMBIOSOL/setup_qiime2#79\79]8;;\

           🧹 Cleaned up unneeded files.                                                            ]8;id=789117;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=510059;file:///content/AtelierSYMBIOSOL/setup_qiime2#68\68]8;;\

           Everything is A-OK. You can start using Qiime 2 now 👍                                  ]8;id=756286;file:///content/AtelierSYMBIOSOL/setup_qiime2\setup_qiime2]8;;\:]8;id=89857;file:///content/AtelierSYMBIOSOL/setup_qiime2#176\176]8;;\

Vérifiez l’installation :

In [9]:
!qiime info

System versions
Python version: 3.10.14
QIIME 2 release: 2025.4
QIIME 2 version: 2025.4.0
q2cli version: 2025.4.0

Installed plugins
alignment: 2025.4.0
composition: 2025.4.0
cutadapt: 2025.4.0
dada2: 2025.4.0
deblur: 2025.4.0
demux: 2025.4.0
diversity: 2025.4.0
diversity-lib: 2025.4.0
emperor: 2025.4.0
empress: 1.2.0
feature-classifier: 2025.4.0
feature-table: 2025.4.0
fragment-insertion: 2025.4.0
longitudinal: 2025.4.0
metadata: 2025.4.0
phylogeny: 2025.4.0
quality-control: 2025.4.0
quality-filter: 2025.4.0
rescript: 2025.4.0
sample-classifier: 2025.4.0
stats: 2025.4.0
taxa: 2025.4.0
types: 2025.4.0
vizard: 0.0.1.dev0
vsearch: 2025.4.0

Application config directory
/usr/local/miniforge3/envs/qiime2/var/q2cli

Config
Config Source: /usr/local/miniforge3/envs/qiime2/etc/qiime2_config.toml

Getting help
To find help and learning resources, visit https://qiime2.org.
To get help with configuring and/or understanding QIIME 2 parallelization, visit https://use.qiime2.org/en/latest/references/parallel-configuration.html

Enregistrez ensuite la version utilisée :

In [10]:
import subprocess

qiime_info = subprocess.run(
    ["qiime", "info"],
    capture_output=True,
    text=True,
    check=True
)

version_file = LOG_ROOT / "qiime-info.txt"
version_file.write_text(qiime_info.stdout)

print(qiime_info.stdout)
print("Version enregistrée dans :", version_file)

System versions
Python version: 3.10.14
QIIME 2 release: 2025.4
QIIME 2 version: 2025.4.0
q2cli version: 2025.4.0

Installed plugins
alignment: 2025.4.0
composition: 2025.4.0
cutadapt: 2025.4.0
dada2: 2025.4.0
deblur: 2025.4.0
demux: 2025.4.0
diversity: 2025.4.0
diversity-lib: 2025.4.0
emperor: 2025.4.0
empress: 1.2.0
feature-classifier: 2025.4.0
feature-table: 2025.4.0
fragment-insertion: 2025.4.0
longitudinal: 2025.4.0
metadata: 2025.4.0
phylogeny: 2025.4.0
quality-control: 2025.4.0
quality-filter: 2025.4.0
rescript: 2025.4.0
sample-classifier: 2025.4.0
stats: 2025.4.0
taxa: 2025.4.0
types: 2025.4.0
vizard: 0.0.1.dev0
vsearch: 2025.4.0

Application config directory
/usr/local/miniforge3/envs/qiime2/var/q2cli

Config
Config Source: /usr/local/miniforge3/envs/qiime2/etc/qiime2_config.toml

Getting help
To find help and learning resources, visit https://qiime2.org.
To get help with configuring and/or understanding QIIME 2 parallelization, visit https://use.qiime2.org/en/latest/references/parallel-configuration.html



Version enregistrée dans : /content/drive/MyDrive/Charlotte_DNA_SIP/07_logs/qiime-info.txt

Étape 8 — Inventorier tous les FASTQ

In [11]:
from pathlib import Path
import pandas as pd
import re

fastq_files = sorted(
    list(RAW_ROOT.rglob("*.fastq.gz"))
    + list(RAW_ROOT.rglob("*.fq.gz"))
    + list(RAW_ROOT.rglob("*.fastq"))
    + list(RAW_ROOT.rglob("*.fq"))
)

records = []

for file_path in fastq_files:
    filename = file_path.name

    if re.search(r"(^|[_\-.])R1([_\-.]|$)", filename, re.IGNORECASE):
        direction = "R1"
    elif re.search(r"(^|[_\-.])R2([_\-.]|$)", filename, re.IGNORECASE):
        direction = "R2"
    else:
        direction = "Non déterminée"

    relative_path = file_path.relative_to(RAW_ROOT)
    path_parts = relative_path.parts

    run = path_parts[0] if len(path_parts) >= 1 else "Inconnu"
    marker = path_parts[1] if len(path_parts) >= 2 else "Inconnu"

    records.append({
        "run": run,
        "marker": marker,
        "direction": direction,
        "filename": filename,
        "size_MB": round(file_path.stat().st_size / 1024**2, 2),
        "absolute_path": str(file_path.resolve()),
    })

inventory = pd.DataFrame(records)

if inventory.empty:
    print("Aucun FASTQ trouvé.")
else:
    display(inventory)
    print("\nNombre total de fichiers :", len(inventory))
    display(
        inventory.groupby(
            ["run", "marker", "direction"],
            dropna=False
        ).size().reset_index(name="nombre_fichiers")
    )

,run,marker,direction,filename,size_MB,absolute_path
0,run3,16S,R1,V1-16S-101-10_S29_L001_R1_001.fastq.gz,16.37,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
1,run3,16S,R2,V1-16S-101-10_S29_L001_R2_001.fastq.gz,19.45,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
2,run3,16S,R1,V1-16S-101-12_S36_L001_R1_001.fastq.gz,12.33,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
3,run3,16S,R2,V1-16S-101-12_S36_L001_R2_001.fastq.gz,14.48,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
4,run3,16S,R1,V1-16S-101-5_S1_L001_R1_001.fastq.gz,0.46,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
...,...,...,...,...,...,...
1598,run5,ITS2,R2,V1-ITS2-327-9_S122_L001_R2_001.fastq.gz,2.97,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
1599,run5,ITS2,R1,V1-ITS2-329-6_S127_L001_R1_001.fastq.gz,1.42,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
1600,run5,ITS2,R2,V1-ITS2-329-6_S127_L001_R2_001.fastq.gz,1.88,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
1601,run5,ITS2,R1,V1-ITS2-329-7_S132_L001_R1_001.fastq.gz,5.21,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
1602,run5,ITS2,R2,V1-ITS2-329-7_S132_L001_R2_001.fastq.gz,7.02,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...

Nombre total de fichiers : 1603

    run marker direction  nombre_fichiers
0  run3    16S        R1              368
1  run3    16S        R2              368
2  run4   ITS2        R1              292
3  run4   ITS2        R2              291
4  run5    16S        R1               78
5  run5    16S        R2               78
6  run5   ITS2        R1               64
7  run5   ITS2        R2               64

Enregistrez l’inventaire :

In [12]:
inventory_file = LOG_ROOT / "fastq-inventory.tsv"

inventory.to_csv(
    inventory_file,
    sep="\t",
    index=False
)

print("Inventaire enregistré dans :", inventory_file)

Inventaire enregistré dans : /content/drive/MyDrive/Charlotte_DNA_SIP/07_logs/fastq-inventory.tsv

**Étape 9 — Vérifier les couples R1/R2**

In [13]:
import pandas as pd

pair_records = []

r1_files = sorted(
    list(RAW_ROOT.rglob("*_R1_*.fastq.gz"))
    + list(RAW_ROOT.rglob("*_R1_*.fq.gz"))
)

for r1 in r1_files:
    r2_name = r1.name.replace("_R1_", "_R2_", 1)
    r2 = r1.parent / r2_name

    provisional_sample_id = re.sub(
        r"_S\d+_L\d+_R1_\d+\.(fastq|fq)\.gz$",
        "",
        r1.name,
        flags=re.IGNORECASE
    )

    relative_path = r1.relative_to(RAW_ROOT)
    path_parts = relative_path.parts

    pair_records.append({
        "run": path_parts[0],
        "marker": path_parts[1],
        "sample_id_provisional": provisional_sample_id,
        "R1": r1.name,
        "R2": r2.name if r2.exists() else "",
        "pair_complete": r2.exists(),
        "R1_path": str(r1.resolve()),
        "R2_path": str(r2.resolve()) if r2.exists() else "",
    })

pairs = pd.DataFrame(pair_records)

display(pairs)

if not pairs.empty:
    print(
        "Couples complets :",
        int(pairs["pair_complete"].sum()),
        "/",
        len(pairs)
    )

    incomplete = pairs.loc[~pairs["pair_complete"]]

    if not incomplete.empty:
        print("\nAttention : fichiers R2 absents")
        display(incomplete)

,run,marker,sample_id_provisional,R1,R2,pair_complete,R1_path,R2_path
0,run3,16S,V1-16S-101-10,V1-16S-101-10_S29_L001_R1_001.fastq.gz,V1-16S-101-10_S29_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
1,run3,16S,V1-16S-101-12,V1-16S-101-12_S36_L001_R1_001.fastq.gz,V1-16S-101-12_S36_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
2,run3,16S,V1-16S-101-5,V1-16S-101-5_S1_L001_R1_001.fastq.gz,V1-16S-101-5_S1_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
3,run3,16S,V1-16S-101-6,V1-16S-101-6_S8_L001_R1_001.fastq.gz,V1-16S-101-6_S8_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
4,run3,16S,V1-16S-101-7,V1-16S-101-7_S15_L001_R1_001.fastq.gz,V1-16S-101-7_S15_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
...,...,...,...,...,...,...,...,...
797,run5,ITS2,V1-ITS2-324-8,V1-ITS2-324-8_S142_L001_R1_001.fastq.gz,V1-ITS2-324-8_S142_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
798,run5,ITS2,V1-ITS2-325-6,V1-ITS2-325-6_S117_L001_R1_001.fastq.gz,V1-ITS2-325-6_S117_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
799,run5,ITS2,V1-ITS2-327-9,V1-ITS2-327-9_S122_L001_R1_001.fastq.gz,V1-ITS2-327-9_S122_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
800,run5,ITS2,V1-ITS2-329-6,V1-ITS2-329-6_S127_L001_R1_001.fastq.gz,V1-ITS2-329-6_S127_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...
801,run5,ITS2,V1-ITS2-329-7,V1-ITS2-329-7_S132_L001_R1_001.fastq.gz,V1-ITS2-329-7_S132_L001_R2_001.fastq.gz,True,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...

Couples complets : 801 / 802

Attention : fichiers R2 absents

,run,marker,sample_id_provisional,R1,R2,pair_complete,R1_path,R2_path
371,run4,ITS2,V1-ITS2-103-11_S242_L001_R1_001 (1).fastq.gz,V1-ITS2-103-11_S242_L001_R1_001 (1).fastq.gz,,False,/content/drive/MyDrive/Charlotte_DNA_SIP/02_ra...,

Enregistrez la table :

In [14]:
pairs_file = LOG_ROOT / "fastq-pairs.tsv"

pairs.to_csv(
    pairs_file,
    sep="\t",
    index=False
)

print("Table des couples enregistrée dans :", pairs_file)

Table des couples enregistrée dans : /content/drive/MyDrive/Charlotte_DNA_SIP/07_logs/fastq-pairs.tsv

**Étape 10 — Examiner le fichier Metadata**
(Pour un fichier Excel)

In [15]:
import pandas as pd

metadata_excel = METADATA_ROOT / "Metadata_original.xlsx"

if not metadata_excel.exists():
    raise FileNotFoundError(
        f"Fichier introuvable : {metadata_excel}"
    )

excel_file = pd.ExcelFile(metadata_excel)

print("Feuilles disponibles :", excel_file.sheet_names)

Feuilles disponibles : ['Feuil1']

Puis, pour lire la première feuille :

In [16]:
metadata_original = pd.read_excel(
    metadata_excel,
    sheet_name=excel_file.sheet_names[0],
    dtype=str
)

print("Dimensions :", metadata_original.shape)
print("Colonnes :", metadata_original.columns.tolist())

display(metadata_original.head(20))

Dimensions : (723, 7)
Colonnes : ['sampleid', 'Index_1', 'Index_2', 'Gene', 'No_parcelle', 'Fraction', 'Unnamed: 6']

         sampleid   Index_1    Index_2 Gene No_parcelle Fraction Unnamed: 6
0   V1_16S_101_UF  PCR-D501  PCR-N716   16S         101       UF        NaN
1   V1_16S_102_UF  PCR-D501  PCR-N718   16S         102       UF        NaN
2   V1_16S_103_UF  PCR-D501  PCR-N719   16S         103       UF        NaN
3   V1_16S_104_UF  PCR-D501  PCR-N720   16S         104       UF        NaN
4   V1_16S_105_UF  PCR-D501   PCR-N721  16S         105       UF        NaN
5   V1_16S_106_UF  PCR-D501   PCR-N722  16S         106       UF        NaN
6   V1_16S_107_UF  PCR-D501   PCR-N723  16S         107       UF        NaN
7   V1_16S_108_UF  PCR-D501   PCR-N724  16S         108       UF        NaN
8   V1_16S_109_UF  PCR-D501   PCR-N726  16S         109       UF        NaN
9   V1_16S_110_UF  PCR-D501   PCR-N727  16S         110       UF        NaN
10  V1_16S_111_UF  PCR-D501   PCR-N728  16S         111       UF        NaN
11  V1_16S_112_UF  PCR-D501   PCR-N729  16S         112       UF        NaN
12  V1_16S_113_UF  PCR-D502  PCR-N716   16S         113       UF        NaN
13  V1_16S_114_UF  PCR-D502  PCR-N718   16S         114       UF        NaN
14  V1_16S_115_UF  PCR-D502  PCR-N719   16S         115       UF        NaN
15  V1_16S_116_UF  PCR-D502  PCR-N720   16S         116       UF        NaN
16  V1_16S_117_UF  PCR-D502   PCR-N721  16S         117       UF        NaN
17  V1_16S_118_UF  PCR-D502   PCR-N722  16S         118       UF        NaN
18  V1_16S_119_UF  PCR-D502   PCR-N723  16S         119       UF        NaN
19  V1_16S_120_UF  PCR-D502   PCR-N724  16S         120       UF        NaN

À ce stade, ne modifiez pas encore les identifiants. Il faudra comparer précisément les noms du fichier Excel avec les noms des FASTQ.

Étape 11 — Copier l’inventaire dans le dépôt GitHub

Dans GitHub, créez cette structure :